version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/progress
      - SPRING_DATASOURCE_USERNAME=progress
      - SPRING_DATASOURCE_PASSWORD=qwertyuiop

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=progress
      - POSTGRES_PASSWORD=qwertyuiop
      - POSTGRES_DATABASE=progress
    ports:
      - "5432:5432"