logging:
  level:
    org.hibernate.SQL: DEBUG
    com.data.warehouse: DEBUG

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers']

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_warehouse
    username: progress
    password: qwertyuiop
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

